# Generated by Django 4.2.2 on 2023-08-02 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_name_task_a_rename_priority_task_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='c',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
